-- Add missing columns to songs table
ALTER TABLE songs ADD COLUMN IF NOT EXISTS artist text;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS track_status text CHECK (track_status IN ('draft', 'pending_approval', 'released'));
ALTER TABLE songs ADD COLUMN IF NOT EXISTS is_released boolean DEFAULT false;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS length_seconds integer;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS audio_file_url text;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS cover_image_url text;

-- Create contacts table if it doesn't exist
CREATE TABLE IF NOT EXISTS contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    contact_type text,
    email text,
    phone text,
    owner_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
);
